### ISSUE TITLE
Ping from worker to master

### ISSUE THREAD

**Issue by Microeinstein** [morrolinux/olive-distributed#7]
Hi,
I just watched your youtube video on this project and wondered:

why would not add a ping functionality (a ping every 30 seconds or so), to allow workers to report they are alive to the master node?

It may help jobs allocation.

**Comment by morrolinux** [comment]
I basically already did that via a watchdog last week, see #5 
Now workers can gracefully terminate in any condition

**Comment by Microeinstein** [comment]
Ah, that's nice 👍🏻
